// Find TODO statements and complete them to build the interactive airline route map.

// TODO: add your uniqname to the HTML (use id #uniqname) file so that your work can be identified 

// TODO: import data using d3.csv()
const dataFile = await d3.csv("data/routes.csv");

const colornone = "#ccc";

// define colors for airlines, you can expand this as needed, WN is Southwest, B6 is JetBlue
const airlineColor = { WN: "orange", B6: "steelblue" };
const airlineName = { WN: "Southwest Airlines", B6: "JetBlue" };

// create options from selector that allows us to view all airlines or filter by a specific airline
const airlines = ["all", ...new Set(dataFile.map(d => d.Airline))];

// build selector from data
const select = d3.select("body")
    .insert("select", "#chart")
    .on("change", function () { draw(this.value); });

select.selectAll("option")
    .data(airlines)
    .join("option")
    .attr("value", d => d)
    .text(d => d === "all" ? "All Airlines" : (airlineName[d] || d)); // TODO: build options from selector that allows us to view all airlines or filter by a specific airline

// helper function to build outgoing links for each leaf node
function bilink(root) {
    // create a map of leaf nodes for quick lookup, using the unique ID generated by the id() function
    const map = new Map(root.leaves().map(d => [id(d), d]));

    // for each leaf node, build an outgoing array of [source, target, airline] tuples
    for (const d of root.leaves()) {
        d.outgoing = d.data.destinations
            .map(({ target, airline, targetRegion }) => [d, map.get(`root/${targetRegion}/${target}`), airline])
            .filter(([, target]) => target !== undefined);
    }

    return root;
}

// helper function to generate a unique ID for each node based on its position in the hierarchy
function id(node) {
    return `${node.parent ? id(node.parent) + "/" : ""}${node.data.name}`;
}

//rebuild hierarchy data and redraw chart on selection change
function draw(airlineFilter) {

    // filter data based on selection, if "all" is selected, use the entire dataset
    const filtered = airlineFilter === "all"
        ? dataFile
        : dataFile.filter(d => d.Airline === airlineFilter);

    // group data by source region and then by source airport
    // Build a map of all unique airports and their regions to ensure they are all in the hierarchy tree
    const airportMap = new Map();
    filtered.forEach(d => {
        airportMap.set(d["Source airport"], d["Source region"]);
        airportMap.set(d["Destination airport"], d["Destination region"]);
    });

    // Group the filtered routes by source airport for easy lookup when building hierarchy children
    const routesBySource = d3.group(filtered, d => d["Source airport"]);

    // Group the complete set of airports by their region for hierarchy transformation
    const airportsByRegion = d3.group(Array.from(airportMap.entries()), ([, region]) => region);

    // transform grouped data into a hierarchy format suitable for the chart
    const hierarchyData = {
        name: "root",
        children: Array.from(airportsByRegion, ([region, airports]) => ({
            name: region,
            children: airports.map(([airport]) => {
                const routes = routesBySource.get(airport) || [];
                return {
                    name: airport,
                    destinations: routes.map(r => ({
                        target: r["Destination airport"],
                        airline: r.Airline,
                        targetRegion: r["Destination region"]
                    }))
                };
            })
        }))
    };

    document.getElementById("chart").innerHTML = "";
    document.getElementById("chart").appendChild(createChart(hierarchyData));
}

draw("all"); // initial draw


// TODO: integrate code from Observable notebook https://observablehq.com/@d3/hierarchical-edge-bundling 
// TODO: edit the tooltip to show the airport code, the region, and the number of outgoing and incoming routes for that airport
// TODO: edit link to show different colors for different airlines, you can use the airlineColor object defined above for reference
// TODO: edit overed and outed functions to highlight connected links and nodes on hover
function createChart(data) {
    const width = 928;
    const radius = width / 2;
    const colorin = "blue";
    const colorout = "red";

    const tree = d3.cluster()
        .size([2 * Math.PI, radius - 100]);

    const root = tree(bilink(d3.hierarchy(data)
        .sort((a, b) => d3.ascending(a.height, b.height) || d3.ascending(a.data.name, b.data.name))));

    // Build incoming connections
    for (const d of root.leaves()) d.incoming = [];
    for (const d of root.leaves()) {
        for (const o of d.outgoing) {
            o[1].incoming.push(o);
        }
    }

    const svg = d3.create("svg")
        .attr("width", width)
        .attr("height", width)
        .attr("viewBox", [-width / 2, -width / 2, width, width])
        .attr("style", "max-width: 100%; height: auto; font: 10px sans-serif;");

    const line = d3.lineRadial()
        .curve(d3.curveBundle.beta(0.85))
        .radius(d => d.y)
        .angle(d => d.x);

    const link = svg.append("g")
        .attr("fill", "none")
        .selectAll("path")
        .data(root.leaves().flatMap(leaf => leaf.outgoing))
        .join("path")
        .style("mix-blend-mode", "multiply")
        .attr("d", ([i, o]) => line(i.path(o)))
        .attr("stroke", ([, , airline]) => airlineColor[airline] || colornone)
        .each(function(d) { d.path = this; });

    const node = svg.append("g")
        .selectAll("g")
        .data(root.leaves())
        .join("g")
        .attr("transform", d => `rotate(${d.x * 180 / Math.PI - 90}) translate(${d.y},0)`)
        .append("text")
        .attr("dy", "0.31em")
        .attr("x", d => d.x < Math.PI ? 6 : -6)
        .attr("text-anchor", d => d.x < Math.PI ? "start" : "end")
        .attr("transform", d => d.x >= Math.PI ? "rotate(180)" : null)
        .text(d => d.data.name)
        .each(function(d) { d.text = this; })
        .on("mouseover", overed)
        .on("mouseout", outed)
        .call(text => text.append("title")
            .text(d => `Airport: ${d.data.name} \nRegion: ${d.parent.data.name} \nOutgoing Routes: ${d.outgoing.length} \nIncoming Routes: ${d.incoming.length}`));

    function overed(event, d) {
        link.style("mix-blend-mode", null);
        link.attr("stroke", colornone); // Dim non-connected links
        
        d3.select(this).attr("font-weight", "bold");
        
        d3.selectAll(d.incoming.map(d => d.path))
            .attr("stroke", colorin)
            .attr("stroke-width", 3)
            .raise();
        d3.selectAll(d.incoming.map(([d]) => d.text)).attr("fill", colorin).attr("font-weight", "bold");
        
        d3.selectAll(d.outgoing.map(d => d.path))
            .attr("stroke", colorout)
            .attr("stroke-width", 3)
            .raise();
        d3.selectAll(d.outgoing.map(([, d]) => d.text)).attr("fill", colorout).attr("font-weight", "bold");
    }

    function outed(event, d) {
        link.style("mix-blend-mode", "multiply");
        link.attr("stroke", ([, , airline]) => airlineColor[airline] || colornone) // Restore airline colors
            .attr("stroke-width", null);
            
        d3.select(this).attr("font-weight", null);
        d3.selectAll(d.incoming.map(([d]) => d.text)).attr("fill", null).attr("font-weight", null);
        d3.selectAll(d.outgoing.map(([, d]) => d.text)).attr("fill", null).attr("font-weight", null);
    }

    return svg.node();
}